const group = {
  label: 'pages',
  strings: {
    // ── Contact page ────────────────────────────────────────────────
    'pages.contact.subjectGeneral': 'General Inquiry',
    'pages.contact.subjectProject': 'Project Information',
    'pages.contact.subjectVisit': 'Site Visit',
    'pages.contact.subjectComplaint': 'Complaint',
    'pages.contact.subjectOther': 'Other',
    'pages.contact.errNamePhone': 'Please fill in your name and phone number',
    'pages.contact.toastSuccess': 'Thank you! Confirmation email & WhatsApp message will be sent shortly.',
    'pages.contact.toastGenericError': 'Something went wrong. Please try again.',
    'pages.contact.toastNetworkError': 'Network error. Please try again.',
    'pages.contact.eyebrow': 'GET IN TOUCH',
    'pages.contact.formTitle': 'Send Us a Message',
    'pages.contact.formSubtitle': 'Fill in the form below and our team will respond within 24 hours.',
    'pages.contact.labelName': 'Name',
    'pages.contact.phName': 'Your full name',
    'pages.contact.labelPhone': 'Phone',
    'pages.contact.phPhone': '01XXX-XXXXXX',
    'pages.contact.labelEmail': 'Email',
    'pages.contact.phEmail': 'your@email.com',
    'pages.contact.labelSubject': 'Subject',
    'pages.contact.phSubject': 'Select a subject',
    'pages.contact.labelMessage': 'Message',
    'pages.contact.phMessage': 'How can we help you?',
    'pages.contact.sending': 'Sending...',
    'pages.contact.sendMessage': 'Send Message',
    'pages.contact.infoTitle': 'Contact Information',
    'pages.contact.infoAddress': 'Office Address',
    'pages.contact.infoPhone': 'Phone',
    'pages.contact.infoEmail': 'Email',
    'pages.contact.infoHours': 'Office Hours',
    'pages.contact.whatsapp': 'Chat on WhatsApp',
    'pages.contact.mapOfficeLocation': 'Office Location',
    'pages.contact.directions': 'Get Directions',
    'pages.contact.faqPrompt': 'Have questions? Check our FAQ section',
    'pages.contact.faqLink': 'Visit FAQ',

    // ── About page (non-DB section headings only) ───────────────────
    'pages.about.storyEyebrow': 'OUR STORY',
    'pages.about.journeyEyebrow': 'OUR JOURNEY',
    'pages.about.journeyTitle': 'The Road, So Far and Ahead',
    'pages.about.journeySubtitle': "A young company's honest ledger — what is done, what is underway, and what comes next.",
    'pages.about.leadershipEyebrow': 'Leadership',
    'pages.about.leadershipTitlePre': 'In their own',
    'pages.about.leadershipTitleEm': 'words',
    'pages.about.leadershipSubtitle': 'No ghostwritten mission statements — the people accountable for this company, on the record.',
    'pages.about.fromThe': 'From the',
    'pages.about.teamEyebrow': 'The Team',
    'pages.about.valuesEyebrow': 'OUR VALUES',
    'pages.about.valuesTitle': 'What We Stand For',
    'pages.about.valuesSubtitle': 'The principles that guide every decision we make and every community we build.',
    'pages.about.approvalsEyebrow': 'Approvals & Utilities',
    'pages.about.approvalsTitle': 'The Bodies Our Work Answers To',
    'pages.about.approvalsSubtitle': 'Our projects are planned and executed around the approvals and utility infrastructure of these public institutions.',

    // ── Privacy page ────────────────────────────────────────────────
    'pages.privacy.heroEyebrow': 'Privacy Policy',
    'pages.privacy.heroTitlePre': 'Your data,',
    'pages.privacy.heroTitleAccent': 'protected',
    'pages.privacy.heroSubtitle': 'How we collect, use, and protect your personal information.',
    'pages.privacy.lastUpdated': 'Last updated:',
    'pages.privacy.contactHeading': 'Get in Touch',

    // ── Terms page ──────────────────────────────────────────────────
    'pages.terms.heroEyebrow': 'Terms & Conditions',
    'pages.terms.heroTitlePre': 'The',
    'pages.terms.heroTitleAccent': 'fine print',
    'pages.terms.heroTitlePost': ', plainly',
    'pages.terms.heroSubtitle': 'Please read these terms carefully before using our services.',
    'pages.terms.lastUpdated': 'Last updated:',
    'pages.terms.contactHeading': 'Contact Us',

    // ── FAQ page ────────────────────────────────────────────────────
    'pages.faq.heroEyebrow': 'The Answers',
    'pages.faq.heroTitlePre': 'Everything you need to',
    'pages.faq.heroTitleAccent': 'know',
    'pages.faq.heroSubtitle': 'Approvals, plot sizes, payment plans, site visits — answered plainly.',
    'pages.faq.searchPlaceholder': 'Search questions...',
    'pages.faq.popularQuestions': 'Popular Questions',
    'pages.faq.statQuestions': 'Questions',
    'pages.faq.statCategories': 'Categories',
    'pages.faq.statMostAsked': 'Most Asked:',
    'pages.faq.wasHelpful': 'Was this helpful?',
    'pages.faq.yes': 'Yes',
    'pages.faq.no': 'No',
    'pages.faq.feedbackYes': 'Thanks for your feedback!',
    'pages.faq.feedbackNo': "We'll improve this answer.",
    'pages.faq.noResultsTitle': 'No questions found',
    'pages.faq.noResultsSubtitle': 'Try a different search term or browse by category',
    'pages.faq.tryTheseTopics': 'Try these topics',
    'pages.faq.askUsDirectly': 'Ask Us Directly',
    'pages.faq.ctaTitle': 'Still have questions?',
    'pages.faq.ctaSubtitle': 'Our team is ready to help. Reach out through any of the channels below.',
    'pages.faq.whatsappUs': 'WhatsApp Us',
    'pages.faq.bookSiteVisit': 'Book a Free Site Visit',
    'pages.faq.contactUs': 'Contact Us',

    // ── Site Visit page ─────────────────────────────────────────────
    'pages.siteVisit.valuePropTransportTitle': 'Free Transport',
    'pages.siteVisit.valuePropTransportDesc': 'Complimentary pickup from our Gulshan-2 office',
    'pages.siteVisit.valuePropGuidanceTitle': 'Expert Guidance',
    'pages.siteVisit.valuePropGuidanceDesc': 'Meet our experienced advisors who will guide you through every detail',
    'pages.siteVisit.valuePropObligationTitle': 'No Obligation',
    'pages.siteVisit.valuePropObligationDesc': 'Visit first, decide at your pace. No pressure, no commitment',
    'pages.siteVisit.projectChandraChaya': 'Chandra Chaya',
    'pages.siteVisit.projectVenturaCity': 'Ventura City',
    'pages.siteVisit.timeSlotMorning': 'Morning 9-12',
    'pages.siteVisit.timeSlotAfternoon': 'Afternoon 12-3',
    'pages.siteVisit.timeSlotLateAfternoon': 'Late Afternoon 3-5',
    'pages.siteVisit.stepBookTitle': 'Book Online',
    'pages.siteVisit.stepBookDesc': 'Fill out the form below',
    'pages.siteVisit.stepConfirmTitle': 'Get Confirmation',
    'pages.siteVisit.stepConfirmDesc': 'We call within 1 hour',
    'pages.siteVisit.stepTransportTitle': 'Free Transport',
    'pages.siteVisit.stepTransportDesc': 'Pickup from Gulshan-2',
    'pages.siteVisit.stepVisitTitle': 'Visit & Explore',
    'pages.siteVisit.stepVisitDesc': 'Tour the site with experts',
    'pages.siteVisit.errName': 'Full name is required',
    'pages.siteVisit.errPhone': 'Phone number is required',
    'pages.siteVisit.errDate': 'Preferred date is required',
    'pages.siteVisit.toastConfirmedTitle': 'Booking Confirmed!',
    'pages.siteVisit.toastConfirmedDesc': 'Our team will confirm your visit within 1 hour via phone call.',
    'pages.siteVisit.toastFailedTitle': 'Booking Failed',
    'pages.siteVisit.toastFailedDesc': 'Something went wrong. Please try again.',
    'pages.siteVisit.toastNetworkTitle': 'Network Error',
    'pages.siteVisit.toastNetworkDesc': 'Please check your connection and try again.',
    'pages.siteVisit.heroEyebrow': 'The Visit',
    'pages.siteVisit.heroTitleLine1': 'Walk the land',
    'pages.siteVisit.heroTitleLine2Pre': 'before you',
    'pages.siteVisit.heroTitleAccent': 'own it',
    'pages.siteVisit.heroSubtitle': "A complimentary guided tour of Purbachal's finest land development — free pickup, no obligation.",
    'pages.siteVisit.howItWorksEyebrow': 'HOW IT WORKS',
    'pages.siteVisit.howItWorksTitlePre': 'How It',
    'pages.siteVisit.howItWorksTitleAccent': 'Works',
    'pages.siteVisit.formEyebrow': 'BOOK A VISIT',
    'pages.siteVisit.formTitle': 'Schedule Your Visit',
    'pages.siteVisit.labelFullName': 'Full Name',
    'pages.siteVisit.phFullName': 'Enter your full name',
    'pages.siteVisit.labelPhone': 'Phone Number',
    'pages.siteVisit.phPhone': '01XXXXXXXXX',
    'pages.siteVisit.labelEmail': 'Email',
    'pages.siteVisit.optional': '(optional)',
    'pages.siteVisit.phEmail': 'your@email.com',
    'pages.siteVisit.labelSelectProject': 'Select Project',
    'pages.siteVisit.phSelectProject': 'Choose a project',
    'pages.siteVisit.labelPreferredDate': 'Preferred Date',
    'pages.siteVisit.labelPreferredTime': 'Preferred Time',
    'pages.siteVisit.phSelectTime': 'Select time slot',
    'pages.siteVisit.labelVisitors': 'Number of Visitors',
    'pages.siteVisit.phVisitors': 'How many visitors?',
    'pages.siteVisit.freeTransportPre': "I'd like free transport from",
    'pages.siteVisit.freeTransportPost': 'office',
    'pages.siteVisit.labelMessage': 'Additional Message',
    'pages.siteVisit.phMessage': 'Any special requirements or questions...',
    'pages.siteVisit.booking': 'Booking...',
    'pages.siteVisit.confirmBooking': 'Confirm Booking',
    'pages.siteVisit.trustSecure': 'Your information is secure',
    'pages.siteVisit.trustNoObligation': 'No obligation to purchase',
    'pages.siteVisit.notePre': 'Our team will confirm your visit within',
    'pages.siteVisit.noteHighlight': '1 hour',
    'pages.siteVisit.notePost': 'via phone call',
    'pages.siteVisit.testimonialsEyebrow': 'TESTIMONIALS',
    'pages.siteVisit.testimonialsTitlePre': 'What Our',
    'pages.siteVisit.testimonialsTitleAccent': 'Visitors',
    'pages.siteVisit.testimonialsTitlePost': 'Say',

    // ── Blog list page ──────────────────────────────────────────────
    'pages.blog.toastSubscribed': 'Successfully subscribed!',
    'pages.blog.toastSubscribedDesc': "You'll receive the latest real estate insights.",
    'pages.blog.toastSubscribeFailed': 'Subscription failed. Please try again.',
    'pages.blog.toastNetworkError': 'Network error. Please try again.',
    'pages.blog.statArticles': 'Articles',
    'pages.blog.statCategories': 'Categories',
    'pages.blog.statLatest': 'Latest:',
    'pages.blog.searchPlaceholder': 'Search articles...',
    'pages.blog.resultsFound': 'results found',
    'pages.blog.resultFound': 'result found',
    'pages.blog.editorsPick': "◆ Editor's Pick",
    'pages.blog.readMore': 'Read More',
    'pages.blog.emptyTitle': 'No articles found',
    'pages.blog.emptyNoResultsPre': 'No results for ',
    'pages.blog.emptyNoResultsPost': '. Try a different search term.',
    'pages.blog.emptyCategory': 'No articles found in this category yet.',
    'pages.blog.clearSearch': 'Clear Search',
    'pages.blog.popularCategories': 'Popular Categories',
    'pages.blog.newsletterPlaceholder': 'Enter your email',
    'pages.blog.subscribe': 'Subscribe',
    'pages.blog.noSpam': 'No spam, unsubscribe anytime.',

    // ── Gallery page ────────────────────────────────────────────────
    'pages.gallery.statPhotos': 'Photos',
    'pages.gallery.statCategories': 'Categories',
    'pages.gallery.statAllProjects': 'All Projects',
    'pages.gallery.dialogTitleFallback': 'Gallery Image',
    'pages.gallery.lightboxHint': '← → to navigate, Esc to close',
    'pages.gallery.ariaPrevious': 'Previous image',
    'pages.gallery.ariaNext': 'Next image',
    'pages.gallery.ariaDownload': 'Download',
    'pages.gallery.ariaClose': 'Close',
    'pages.gallery.ctaBookVisit': 'Book a Visit',
    'pages.gallery.ctaBrowseProjects': 'Browse Projects',

    // ── Blog article page ───────────────────────────────────────────
    'pages.blogArticle.toastLinkCopied': 'Link copied!',
    'pages.blogArticle.toastCopyFailed': 'Failed to copy link',
    'pages.blogArticle.breadcrumbHome': 'Home',
    'pages.blogArticle.breadcrumbBlog': 'Blog',
    'pages.blogArticle.shareArticle': 'Share this article',
    'pages.blogArticle.shareWhatsApp': 'WhatsApp',
    'pages.blogArticle.shareFacebook': 'Facebook',
    'pages.blogArticle.shareX': 'X',
    'pages.blogArticle.copied': 'Copied!',
    'pages.blogArticle.copyLink': 'Copy Link',
    'pages.blogArticle.tableOfContents': 'Table of Contents',
    'pages.blogArticle.viewAllPosts': 'View All Posts',
    'pages.blogArticle.ctaTitle': 'Interested in investing?',
    'pages.blogArticle.ctaSubtitle': 'Get in touch with our team to explore premium plots in Purbachal.',
    'pages.blogArticle.contactUs': 'Contact Us',
    'pages.blogArticle.relatedArticles': 'Related Articles',
    'pages.blogArticle.notFoundTitle': 'Article Not Found',
    'pages.blogArticle.notFoundMessage': "The article you're looking for doesn't exist.",
    'pages.blogArticle.backToBlog': 'Back to Blog',

    // ── 404 / Not Found page ────────────────────────────────────────
    'pages.notFound.title': 'Page Not Found',
    'pages.notFound.message': 'The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.',
    'pages.notFound.backHome': 'Back to Home',
    'pages.notFound.browseProjects': 'Browse Projects',
    'pages.notFound.helpfulLinks': 'Helpful links:',
    'pages.notFound.linkAbout': 'About Us',
    'pages.notFound.linkContact': 'Contact',
    'pages.notFound.linkBlog': 'Blog',
    'pages.notFound.linkFaq': 'FAQ',
  } as Record<string, string>,
}
export default group
