const group = {
  label: 'projects',
  strings: {
    /* ── ProjectsPage (list) ── */
    'projects.list.filtersLabel': 'Filters',
    'projects.list.typeResidential': 'Residential',
    'projects.list.typeCommercial': 'Commercial',
    'projects.list.budgetPrefix': 'Budget:',
    'projects.list.clearFilters': 'Clear filters',
    'projects.list.searchPlaceholder': 'Search by name, location, or features...',
    'projects.list.clearSearchAria': 'Clear search',
    'projects.list.statProjects': 'Projects',
    'projects.list.statOngoing': 'Ongoing',
    'projects.list.statUpcoming': 'Upcoming',
    'projects.list.tabAll': 'All',
    'projects.list.tabOngoing': 'Ongoing',
    'projects.list.tabUpcoming': 'Upcoming',
    'projects.list.tabReady': 'Ready',
    'projects.list.tabCompleted': 'Completed',
    'projects.list.gridViewAria': 'Grid view',
    'projects.list.listViewAria': 'List view',
    'projects.list.showing': 'Showing',
    'projects.list.showingOf': 'of',
    'projects.list.showingProjects': 'projects',
    'projects.list.emptyTitle': 'No projects found',
    'projects.list.emptyTitleSearch': ' matching your search',
    'projects.list.emptyTitleCategory': ' for this category',
    'projects.list.emptyBodySearch': 'Try a different search term or clear the search to see all projects.',
    'projects.list.emptyBodyCategory': 'Try selecting a different category to explore our projects.',
    'projects.list.clearSearch': 'Clear Search',
    'projects.list.clearFiltersBtn': 'Clear Filters',
    'projects.list.viewAllProjects': 'View All Projects',
    'projects.list.tryCategories': 'Try these categories:',
    'projects.list.viewDetails': 'View Details',
    'projects.list.bookVisit': 'Book Visit',
    'projects.list.compareAria': 'Compare',
    'projects.list.ctaLink': 'Get in Touch',

    /* ── CompareProjects (compare) ── */
    'projects.compare.floatTitle': 'Compare',
    'projects.compare.projectSingular': 'project',
    'projects.compare.projectsPlural': 'projects',
    'projects.compare.noneSelected': 'No projects selected',
    'projects.compare.buttonLabel': 'Compare',
    'projects.compare.floatAria': 'Compare projects',
    'projects.compare.dialogTitle': 'Compare Projects',
    'projects.compare.dialogDesc': 'Compare up to 3 projects side by side',
    'projects.compare.clearAll': 'Clear All',
    'projects.compare.oneSelected': '1 project selected – add 1 more',
    'projects.compare.selectAtLeastTwo': 'Select at least 2 projects to compare',
    'projects.compare.addProject': 'Add Project',
    'projects.compare.getStartedHint': 'Click the compare icon on project cards to get started',
    'projects.compare.removeAria': 'Remove',
    'projects.compare.viewDetails': 'View Details →',
    'projects.compare.rowLocation': 'Location',
    'projects.compare.rowTotalArea': 'Total Area',
    'projects.compare.rowPlotSize': 'Plot Size',
    'projects.compare.rowPriceRange': 'Price Range',
    'projects.compare.rowStatus': 'Status',
    'projects.compare.rowFeatures': 'Key Features',
    'projects.compare.bestValue': 'Best Value',
    'projects.compare.recommendation': 'Our Recommendation',
    'projects.compare.availableNow': 'Available Now',
    'projects.compare.comingSoon': 'Coming Soon',

    /* ── PaymentPlans (payment) ── */
    'projects.payment.label': 'INVESTMENT PLANS',
    'projects.payment.heading': 'Transparent Pricing, Flexible Payment',
    'projects.payment.subheading': 'Choose from our range of residential plots with easy installment options starting from ৳12 Lakh',
    'projects.payment.emiBadge': '0% Interest EMI Available for up to 36 Months',
    'projects.payment.startingFrom': 'Starting from',
    'projects.payment.getStarted': 'Get Started',
    'projects.payment.enquireNow': 'Enquire Now',
    'projects.payment.trustLine': 'All prices are inclusive of registration. EMI options available for up to 36 months.',

    /* ── EMICalculator (emi) ── */
    'projects.emi.title': 'EMI Calculator',
    'projects.emi.loanAmountLabel': 'Loan Amount (BDT)',
    'projects.emi.loanAmountPlaceholder': 'e.g. 5000000',
    'projects.emi.interestRateLabel': 'Interest Rate (% per year)',
    'projects.emi.interestRatePlaceholder': 'e.g. 9.5',
    'projects.emi.tenureLabel': 'Loan Tenure (years)',
    'projects.emi.tenurePlaceholder': 'e.g. 5',
    'projects.emi.calculateBtn': 'Calculate EMI',
    'projects.emi.monthlyEmi': 'Monthly EMI',
    'projects.emi.totalInterest': 'Total Interest',
    'projects.emi.totalPayment': 'Total Payment',
    'projects.emi.principal': 'Principal',
    'projects.emi.interest': 'Interest',

    /* ── PropertySearchBar (search) ── */
    'projects.search.fieldType': 'Project Type',
    'projects.search.fieldBudget': 'Budget Range',
    'projects.search.fieldSize': 'Plot Size',
    'projects.search.searchBtn': 'Search',

    /* ── MapImageViewer (map) ── */
    'projects.map.enlarge': 'Enlarge',
    'projects.map.closeAria': 'Close',

    /* ── RajukSeal (seal) ── */
    'projects.seal.aria': 'Planned per RAJUK policy',
    'projects.seal.ringText': 'PER RAJUK POLICY · MATRICA · PURBACHAL ·',

    /* ── ProjectDetailPage (detail) ── */
    // Section nav
    'projects.detail.navOverview': 'Overview',
    'projects.detail.navAmenities': 'Amenities',
    'projects.detail.navLocation': 'Location',
    'projects.detail.navGallery': 'Gallery',
    'projects.detail.navDownloads': 'Downloads',
    'projects.detail.navFaq': 'FAQ',
    'projects.detail.inquireNav': 'Inquire',
    // Not-found state
    'projects.detail.notFoundTitle': 'Project Not Found',
    'projects.detail.notFoundBody': 'The project you are looking for does not exist.',
    'projects.detail.viewAllProjects': 'View All Projects',
    // WhatsApp prefill
    'projects.detail.waMessage': "Hi {company}! I'm interested in {project}. Please share details.",
    // Hero
    'projects.detail.crumbHome': 'Home',
    'projects.detail.crumbProjects': 'Projects',
    'projects.detail.getBrochure': 'Get the Brochure',
    'projects.detail.bookSiteVisit': 'Book a Site Visit',
    // Overview
    'projects.detail.overviewEyebrow': 'The Project',
    'projects.detail.aboutPrefix': 'About',
    'projects.detail.devStatusTitle': 'Development Status',
    'projects.detail.devStatusNote': 'Updated as work proceeds',
    'projects.detail.atAGlance': 'At a Glance',
    'projects.detail.specLocation': 'Location',
    'projects.detail.viewLayoutPlan': 'View Layout Plan',
    'projects.detail.downloadBrochure': 'Download Brochure',
    // Amenities
    'projects.detail.amenitiesEyebrow': 'Planned Amenities',
    'projects.detail.amenitiesTitle': 'Planned for a',
    'projects.detail.amenitiesTitleEm': 'whole life',
    'projects.detail.amenitiesIntro': 'The master plan reserves space for daily life — not just plots. These facilities are part of the plan and are delivered progressively.',
    // Location
    'projects.detail.locationEyebrow': 'Location',
    'projects.detail.locationTitle': 'Where it',
    'projects.detail.locationTitleEm': 'stands',
    'projects.detail.clickMapEnlarge': 'Click the map to enlarge',
    'projects.detail.distancesTitle': 'Distances',
    'projects.detail.distancesNote': 'Approximate, by road.',
    'projects.detail.openGoogleMaps': 'Open in Google Maps',
    'projects.detail.downloadLocationMap': 'Download Location Map',
    // Gallery
    'projects.detail.galleryEyebrow': 'Gallery',
    'projects.detail.galleryTitle': 'The land,',
    'projects.detail.galleryTitleEm': 'as it is',
    // Downloads
    'projects.detail.documentsEyebrow': 'Documents',
    'projects.detail.documentsTitle': 'Read before you',
    'projects.detail.documentsTitleEm': 'decide',
    'projects.detail.documentsIntro': 'The layout plan, location map, and brochure — view them in your browser or download and share with your family.',
    'projects.detail.docDescLayout': 'The full master plan — roads, plot grid, and reserved amenity blocks.',
    'projects.detail.docDescLocation': 'Where the project sits and how to reach it, with key landmarks marked.',
    'projects.detail.docDescBrochure': 'The complete overview — specifications, amenities, pricing, and terms.',
    'projects.detail.docView': 'View',
    'projects.detail.docDownload': 'Download',
    // FAQ
    'projects.detail.faqEyebrow': 'Questions',
    'projects.detail.faqTitle': 'Asked',
    'projects.detail.faqTitleEm': 'often',
    // Site-visit band
    'projects.detail.visitBandTitle': 'Walk the land before you',
    'projects.detail.visitBandTitleEm': 'own it',
    'projects.detail.visitBandBody1': 'Free guided visit with pickup from our',
    'projects.detail.visitBandBody2': 'office. No obligation.',
    'projects.detail.whatsappUs': 'WhatsApp Us',
    // Related
    'projects.detail.relatedEyebrow': 'More Projects',
    'projects.detail.relatedTitle': 'Also by',
    'projects.detail.relatedTitleEm': 'Matrica',
    // Mobile bar
    'projects.detail.mobileCall': 'Call',
    'projects.detail.mobileWhatsapp': 'WhatsApp',
    'projects.detail.mobileBrochure': 'Brochure',
    // Shared toasts / interpolation
    'projects.detail.workingHours': 'working hours.',
    'projects.detail.toastError': 'Something went wrong. Please try again.',
    'projects.detail.toastNetwork': 'Network error. Please try again.',
    'projects.detail.toastNamePhone': 'Please add your name and phone number',
    // Callback card
    'projects.detail.callbackDonePrefix': 'Usually within',
    'projects.detail.callbackDoneTitle': "We'll call you shortly.",
    'projects.detail.callbackTitle': 'Prefer a call?',
    'projects.detail.callbackDescPrefix': 'Leave your number — a land advisor calls you back within',
    'projects.detail.placeholderName': 'Your name',
    'projects.detail.placeholderPhone': '01XXX-XXXXXX',
    'projects.detail.requestCallback': 'Request Callback',
    'projects.detail.callbackSpamPrefix': 'No spam. One call about',
    'projects.detail.callbackSpamSuffix': ', nothing else.',
    // Gallery lightbox
    'projects.detail.closeAria': 'Close',
    'projects.detail.prevAria': 'Previous',
    'projects.detail.nextAria': 'Next',
    // Inquire form
    'projects.detail.inquireToastNamePhone': 'Please fill in your name and phone number',
    'projects.detail.inquireSuccessPrefix': 'Thank you! Our team will contact you within',
    'projects.detail.inquireEyebrow': 'Inquire',
    'projects.detail.inquireTitle': 'Interested in',
    'projects.detail.inquireDescPrefix': "Tell us what you're looking for — a land advisor responds within",
    'projects.detail.labelName': 'Name *',
    'projects.detail.placeholderFullName': 'Your full name',
    'projects.detail.labelPhone': 'Phone *',
    'projects.detail.labelEmail': 'Email',
    'projects.detail.placeholderEmail': 'your@email.com',
    'projects.detail.placeholderEmailOptional': 'Email (optional)',
    'projects.detail.labelPlotSize': 'Preferred Plot Size',
    'projects.detail.optionNotSure': 'Not sure yet',
    'projects.detail.optionCombined': '10+ Katha / Combined',
    'projects.detail.labelMessage': 'Message',
    'projects.detail.placeholderMessage': 'Anything specific — budget, timeline, corner plot…',
    'projects.detail.submitting': 'Submitting…',
    'projects.detail.submitInquiry': 'Submit Inquiry',
    'projects.detail.consentText': 'By submitting, you agree to be contacted about Matrica projects. We never share your information.',
    // Doc gate modal
    'projects.detail.gateUnlockedToast': 'Unlocked — all project documents are now open for you.',
    'projects.detail.gateDescPrefix': 'Leave your name and number and the document opens instantly — and every other',
    'projects.detail.gateDescSuffix': 'document unlocks with it. One-time, no spam.',
    'projects.detail.gateDownload': 'Unlock & Download',
    'projects.detail.gateView': 'Unlock & View',
  } as Record<string, string>,
}
export default group
